/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MonoRouteImport } from './routes/mono'
import { Route as R5RouteImport } from './routes/5'
import { Route as R4RouteImport } from './routes/4'
import { Route as R3RouteImport } from './routes/3'
import { Route as R2RouteImport } from './routes/2'
import { Route as R1RouteImport } from './routes/1'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WatchPublicIdRouteImport } from './routes/watch.$publicId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ForVideoEditorsRouteImport } from './routes/for.video-editors'
import { Route as ForAgenciesRouteImport } from './routes/for.agencies'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardTeamIdRouteImport } from './routes/dashboard/$teamId'
import { Route as CompareWipsterRouteImport } from './routes/compare.wipster'
import { Route as CompareFrameioRouteImport } from './routes/compare.frameio'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardTeamIdIndexRouteImport } from './routes/dashboard/$teamId.index'
import { Route as DashboardTeamIdSettingsRouteImport } from './routes/dashboard/$teamId.settings'
import { Route as DashboardTeamIdProjectIdRouteImport } from './routes/dashboard/$teamId.$projectId'
import { Route as DashboardTeamIdProjectIdIndexRouteImport } from './routes/dashboard/$teamId.$projectId.index'
import { Route as DashboardTeamIdProjectIdVideoIdRouteImport } from './routes/dashboard/$teamId.$projectId.$videoId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MonoRoute = MonoRouteImport.update({
  id: '/mono',
  path: '/mono',
  getParentRoute: () => rootRouteImport,
} as any)
const R5Route = R5RouteImport.update({
  id: '/5',
  path: '/5',
  getParentRoute: () => rootRouteImport,
} as any)
const R4Route = R4RouteImport.update({
  id: '/4',
  path: '/4',
  getParentRoute: () => rootRouteImport,
} as any)
const R3Route = R3RouteImport.update({
  id: '/3',
  path: '/3',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const R1Route = R1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const WatchPublicIdRoute = WatchPublicIdRouteImport.update({
  id: '/watch/$publicId',
  path: '/watch/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVideoEditorsRoute = ForVideoEditorsRouteImport.update({
  id: '/for/video-editors',
  path: '/for/video-editors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for/agencies',
  path: '/for/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamIdRoute = DashboardTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CompareWipsterRoute = CompareWipsterRouteImport.update({
  id: '/compare/wipster',
  path: '/compare/wipster',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFrameioRoute = CompareFrameioRouteImport.update({
  id: '/compare/frameio',
  path: '/compare/frameio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdIndexRoute = DashboardTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeamIdRoute,
} as any)
const DashboardTeamIdSettingsRoute = DashboardTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardTeamIdRoute,
} as any)
const DashboardTeamIdProjectIdRoute =
  DashboardTeamIdProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardTeamIdRoute,
  } as any)
const DashboardTeamIdProjectIdIndexRoute =
  DashboardTeamIdProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeamIdProjectIdRoute,
  } as any)
const DashboardTeamIdProjectIdVideoIdRoute =
  DashboardTeamIdProjectIdVideoIdRouteImport.update({
    id: '/$videoId',
    path: '/$videoId',
    getParentRoute: () => DashboardTeamIdProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamId/$projectId': typeof DashboardTeamIdProjectIdRouteWithChildren
  '/dashboard/$teamId/settings': typeof DashboardTeamIdSettingsRoute
  '/dashboard/$teamId/': typeof DashboardTeamIdIndexRoute
  '/dashboard/$teamId/$projectId/$videoId': typeof DashboardTeamIdProjectIdVideoIdRoute
  '/dashboard/$teamId/$projectId/': typeof DashboardTeamIdProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$teamId/settings': typeof DashboardTeamIdSettingsRoute
  '/dashboard/$teamId': typeof DashboardTeamIdIndexRoute
  '/dashboard/$teamId/$projectId/$videoId': typeof DashboardTeamIdProjectIdVideoIdRoute
  '/dashboard/$teamId/$projectId': typeof DashboardTeamIdProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/mono': typeof MonoRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/frameio': typeof CompareFrameioRoute
  '/compare/wipster': typeof CompareWipsterRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/for/agencies': typeof ForAgenciesRoute
  '/for/video-editors': typeof ForVideoEditorsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/watch/$publicId': typeof WatchPublicIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$teamId/$projectId': typeof DashboardTeamIdProjectIdRouteWithChildren
  '/dashboard/$teamId/settings': typeof DashboardTeamIdSettingsRoute
  '/dashboard/$teamId/': typeof DashboardTeamIdIndexRoute
  '/dashboard/$teamId/$projectId/$videoId': typeof DashboardTeamIdProjectIdVideoIdRoute
  '/dashboard/$teamId/$projectId/': typeof DashboardTeamIdProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/1'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/compare/frameio'
    | '/compare/wipster'
    | '/dashboard/$teamId'
    | '/dashboard/profile'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$publicId'
    | '/dashboard/'
    | '/dashboard/$teamId/$projectId'
    | '/dashboard/$teamId/settings'
    | '/dashboard/$teamId/'
    | '/dashboard/$teamId/$projectId/$videoId'
    | '/dashboard/$teamId/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/compare/frameio'
    | '/compare/wipster'
    | '/dashboard/profile'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$publicId'
    | '/dashboard'
    | '/dashboard/$teamId/settings'
    | '/dashboard/$teamId'
    | '/dashboard/$teamId/$projectId/$videoId'
    | '/dashboard/$teamId/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/1'
    | '/2'
    | '/3'
    | '/4'
    | '/5'
    | '/mono'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/compare/frameio'
    | '/compare/wipster'
    | '/dashboard/$teamId'
    | '/dashboard/profile'
    | '/for/agencies'
    | '/for/video-editors'
    | '/invite/$token'
    | '/share/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/watch/$publicId'
    | '/dashboard/'
    | '/dashboard/$teamId/$projectId'
    | '/dashboard/$teamId/settings'
    | '/dashboard/$teamId/'
    | '/dashboard/$teamId/$projectId/$videoId'
    | '/dashboard/$teamId/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  R1Route: typeof R1Route
  R2Route: typeof R2Route
  R3Route: typeof R3Route
  R4Route: typeof R4Route
  R5Route: typeof R5Route
  MonoRoute: typeof MonoRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  CompareFrameioRoute: typeof CompareFrameioRoute
  CompareWipsterRoute: typeof CompareWipsterRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  ForVideoEditorsRoute: typeof ForVideoEditorsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  WatchPublicIdRoute: typeof WatchPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mono': {
      id: '/mono'
      path: '/mono'
      fullPath: '/mono'
      preLoaderRoute: typeof MonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5': {
      id: '/5'
      path: '/5'
      fullPath: '/5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4': {
      id: '/4'
      path: '/4'
      fullPath: '/4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3': {
      id: '/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2': {
      id: '/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1': {
      id: '/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/watch/$publicId': {
      id: '/watch/$publicId'
      path: '/watch/$publicId'
      fullPath: '/watch/$publicId'
      preLoaderRoute: typeof WatchPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/video-editors': {
      id: '/for/video-editors'
      path: '/for/video-editors'
      fullPath: '/for/video-editors'
      preLoaderRoute: typeof ForVideoEditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/agencies': {
      id: '/for/agencies'
      path: '/for/agencies'
      fullPath: '/for/agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$teamId': {
      id: '/dashboard/$teamId'
      path: '/$teamId'
      fullPath: '/dashboard/$teamId'
      preLoaderRoute: typeof DashboardTeamIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/compare/wipster': {
      id: '/compare/wipster'
      path: '/compare/wipster'
      fullPath: '/compare/wipster'
      preLoaderRoute: typeof CompareWipsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/frameio': {
      id: '/compare/frameio'
      path: '/compare/frameio'
      fullPath: '/compare/frameio'
      preLoaderRoute: typeof CompareFrameioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamId/': {
      id: '/dashboard/$teamId/'
      path: '/'
      fullPath: '/dashboard/$teamId/'
      preLoaderRoute: typeof DashboardTeamIdIndexRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/settings': {
      id: '/dashboard/$teamId/settings'
      path: '/settings'
      fullPath: '/dashboard/$teamId/settings'
      preLoaderRoute: typeof DashboardTeamIdSettingsRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/$projectId': {
      id: '/dashboard/$teamId/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$teamId/$projectId'
      preLoaderRoute: typeof DashboardTeamIdProjectIdRouteImport
      parentRoute: typeof DashboardTeamIdRoute
    }
    '/dashboard/$teamId/$projectId/': {
      id: '/dashboard/$teamId/$projectId/'
      path: '/'
      fullPath: '/dashboard/$teamId/$projectId/'
      preLoaderRoute: typeof DashboardTeamIdProjectIdIndexRouteImport
      parentRoute: typeof DashboardTeamIdProjectIdRoute
    }
    '/dashboard/$teamId/$projectId/$videoId': {
      id: '/dashboard/$teamId/$projectId/$videoId'
      path: '/$videoId'
      fullPath: '/dashboard/$teamId/$projectId/$videoId'
      preLoaderRoute: typeof DashboardTeamIdProjectIdVideoIdRouteImport
      parentRoute: typeof DashboardTeamIdProjectIdRoute
    }
  }
}

interface DashboardTeamIdProjectIdRouteChildren {
  DashboardTeamIdProjectIdVideoIdRoute: typeof DashboardTeamIdProjectIdVideoIdRoute
  DashboardTeamIdProjectIdIndexRoute: typeof DashboardTeamIdProjectIdIndexRoute
}

const DashboardTeamIdProjectIdRouteChildren: DashboardTeamIdProjectIdRouteChildren =
  {
    DashboardTeamIdProjectIdVideoIdRoute: DashboardTeamIdProjectIdVideoIdRoute,
    DashboardTeamIdProjectIdIndexRoute: DashboardTeamIdProjectIdIndexRoute,
  }

const DashboardTeamIdProjectIdRouteWithChildren =
  DashboardTeamIdProjectIdRoute._addFileChildren(
    DashboardTeamIdProjectIdRouteChildren,
  )

interface DashboardTeamIdRouteChildren {
  DashboardTeamIdProjectIdRoute: typeof DashboardTeamIdProjectIdRouteWithChildren
  DashboardTeamIdSettingsRoute: typeof DashboardTeamIdSettingsRoute
  DashboardTeamIdIndexRoute: typeof DashboardTeamIdIndexRoute
}

const DashboardTeamIdRouteChildren: DashboardTeamIdRouteChildren = {
  DashboardTeamIdProjectIdRoute: DashboardTeamIdProjectIdRouteWithChildren,
  DashboardTeamIdSettingsRoute: DashboardTeamIdSettingsRoute,
  DashboardTeamIdIndexRoute: DashboardTeamIdIndexRoute,
}

const DashboardTeamIdRouteWithChildren = DashboardTeamIdRoute._addFileChildren(
  DashboardTeamIdRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardTeamIdRoute: typeof DashboardTeamIdRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTeamIdRoute: DashboardTeamIdRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  R1Route: R1Route,
  R2Route: R2Route,
  R3Route: R3Route,
  R4Route: R4Route,
  R5Route: R5Route,
  MonoRoute: MonoRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  CompareFrameioRoute: CompareFrameioRoute,
  CompareWipsterRoute: CompareWipsterRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  ForVideoEditorsRoute: ForVideoEditorsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  WatchPublicIdRoute: WatchPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
